name: CI
on: [push]

jobs:
  check-ts:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node: [18]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/cache/restore@v3.2.5
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}-node-v${{ matrix.node }}

      # Source: https://nextjs.org/docs/advanced-features/ci-build-caching
      - name: Cache NextJS Files
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/frontend/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-

      - name: Install Node.js dependencies
        if: "steps.yarn-cache.outputs.cache-hit != 'true'"
        run: yarn --frozen-lockfile

      - uses: actions/cache/save@v3.2.5
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}-node-v${{ matrix.node }}

      - name: Lint toolkit
        run: |
          yarn workspace @robinplatform/toolkit run lint

      - name: Build toolkit
        run: |
          yarn workspace @robinplatform/toolkit run build

      - name: Lint frontend
        run: |
          yarn workspace @robinplatform/frontend run lint

      - name: Build frontend
        run: |
          yarn workspace @robinplatform/frontend run build
