name: Check TS
on: [push]

jobs:
  check-ts:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - id: node-version
        name: Get node version
        run: |
          echo "version=`cat .nvmrc`" >> $GITHUB_OUTPUT

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.node-version.outputs.version }}

      - name: Install Node.js dependencies
        run: |
          yarn

          if ! test -z "`git diff --stat`"; then
            echo "yarn produced changes, exiting"
            git diff --name-only | cat
            exit 1
          fi

      - name: Lint toolkit
        run: |
          yarn workspace @robinplatform/toolkit run lint

      - name: Build toolkit
        run: |
          yarn workspace @robinplatform/toolkit run build

      - name: Lint frontend
        run: |
          yarn workspace @robinplatform/frontend run lint

      - name: Build frontend
        run: |
          yarn workspace @robinplatform/frontend run build
