name: Check Go
on: [workflow_dispatch]

jobs:
  check-go:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: ~1.20

      - name: Download go modules
        run: |
          cd backend/
          go mod download

      - name: Format
        run: |
          cd backend/
          if ! test -z "`gofmt -s -l .`"; then
            gofmt -s -l .
            exit 1
          fi

      - name: Generate
        run: |
          # Generating a pseudo frontend build so that vet
          # does not complain about the lack of an embed target
          mkdir ./frontend/out
          echo 'hello' > ./frontend/out/index.html

          # Run generate for both targets
          cd backend/
          go generate -x ./...
          go generate -x -tags prod ./...

      - name: Vet
        run: |
          cd backend/
          go vet ./...
          go vet -tags prod ./...

      - name: Test
        run: |
          cd backend/
          go test -v -race ./...
