name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: ~1.20

      - name: Setup Golang caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-

      - name: Download go modules
        run: |
          cd backend/
          go mod download

      - name: Format
        run: |
          cd backend/
          if ! test -z "`gofmt -s -l .`"; then
            gofmt -s -l .
            exit 1
          fi

      - name: Generate
        run: |
          cd backend/
          go generate ./...

      - name: Vet
        run: |
          cd backend/
          go vet ./...

      - name: Test
        run: |
          cd backend/
          go test ./...
