name: Release

on:
  workflow_run:
    workflows: ["Check TS", "Check Go"]
    branches: [main, nightly]
    types: 
      - completed

jobs:
  check-ts:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node: [18]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: ~1.20

      - name: Setup Golang caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-

      - name: Download go modules
        run: |
          cd backend/
          go mod download

      - name: Generate
        run: |
          cd backend/
          go generate -x ./...

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/cache/restore@v3.2.5
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}-node-v${{ matrix.node }}

      # Source: https://nextjs.org/docs/advanced-features/ci-build-caching
      - name: Cache NextJS Files
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-

      - name: Build toolkit
        run: |
          yarn workspace @robinplatform/toolkit run build

      - name: Build frontend
        if: "github.ref == 'refs/heads/main' || github.ref == 'refs/heads/nightly'"
        run: |
          yarn workspace @robinplatform/frontend run build

      - name: Release nightly
        if: "github.ref == 'refs/heads/nightly'"
        run: |
          yarn workspace @robinplatform/backend run build nightly
      
      - name: Release beta
        if: "github.ref == 'refs/heads/main'"
        run: |
          yarn workspace @robinplatform/backend run build beta
