name: Release
on: [push]

jobs:
  release:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node: [18]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: ~1.20

      - name: Download go modules
        run: |
          cd backend/
          go mod download

      - name: Generate
        run: |
          cd backend/
          go generate -x ./...

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Node.js dependencies
        run: yarn

      - name: Build toolkit
        run: |
          yarn workspace @robinplatform/toolkit run build

      - name: Build frontend
        run: |
          yarn workspace @robinplatform/frontend run build
      
      - name: Install s3cmd
        run: |
          pip3 install s3cmd --no-cache
      
      - name: Configure s3cmd
        env:
          S3CFG: ${{ secrets.S3CFG }}
        run: |
          echo $S3CFG | base64 --decode > ~/.s3cfg

      - name: Release nightly
        if: "github.ref == 'refs/heads/nightly' || github.ref == 'refs/heads/release'"
        run: |
          yarn workspace @robinplatform/backend run release nightly
      
      - name: Release beta
        if: "github.ref == 'refs/heads/main'"
        run: |
          yarn workspace @robinplatform/backend run release beta
